cargo-features = ["different-binary-name"]

[package]
name = "my-project"
version = "0.1.0"
edition = "2021"
rust-version = "1.81.0"
autobins = false
autoexamples = false
autotests = false
autobenches = false

[[bin]]
name = "my-project"
filename = "my-project.fap"
bench = false
test = false

[dependencies]
flipperzero = { version = "0.14.0" }
flipperzero-sys = { version = "0.14.0" }
flipperzero-rt = { version = "0.14.0" }
